// Generated by CoffeeScript 1.4.0
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['jquery', 'backbone', 'application/views/mainView', 'application/models/app'], function($, Backbone, MainView, App) {
  var Router;
  return Router = (function(_super) {

    __extends(Router, _super);

    Router.prototype.routes = {
      'connexion': 'connectScreen',
      'admin': "adminScreen",
      'conference/:ordId': 'conferenceScreen',
      'anime/:confId': 'animeScreen',
      '*actions': 'adminScreen'
    };

    function Router(socket) {
      console.log(socket);
      this.socket = socket;
      console.log(this.socket);
      Router.__super__.constructor.call(this, this.routes);
    }

    Router.prototype.initialize = function() {
      var _this = this;
      console.log("router initialize");
      console.log("socket: ", this.socket);
      this.app = new App();
      this.mainView = new MainView({
        model: this.app
      });
      this.mainView.on('sendslide', function(data) {
        return _this.trigger('send', data);
      });
      this.mainView.on('removeslide', function(data) {
        return _this.trigger('remove', data);
      });
      this.mainView.on('saveslide', function(data) {
        return _this.trigger('saveslide', data);
      });
      this.mainView.on('deleteSlide', function(data) {
        return _this.trigger('deleteSlide', data);
      });
      this.mainView.on('updateSlide', function(data) {
        return _this.trigger('updateSlide', data);
      });
      this.mainView.on('newConference', function(data) {
        console.log('new conf');
        return _this.trigger('newConference', data);
      });
      this.mainView.on('newOrganisation', function(data) {
        return _this.trigger('newOrganisation', data);
      });
      this.mainView.on('deleteorg', function(data) {
        return _this.trigger('deleteorg', data);
      });
      this.mainView.on('deleteconf', function(data) {
        return _this.trigger('deleteconf', data);
      });
      this.mainView.on('updateorg', function(data) {
        return _this.trigger('updateorg', data);
      });
      this.trigger('admiRoute');
      return Backbone.history.start();
    };

    Router.prototype.connectScreen = function() {
      return console.log("nothing for now ");
    };

    Router.prototype.adminScreen = function() {
      $(".confplus").parent().hide();
      return console.log("nothing for now");
    };

    Router.prototype.conferenceScreen = function(orgId) {
      var _this = this;
      console.log("listing confs");
      $('.adminScreen').fadeIn(function() {
        return $('.animeScreen').fadeOut();
      });
      console.log("allo");
      return this.trigger('organisationChoosed', orgId);
    };

    Router.prototype.animeScreen = function(confId) {
      var _this = this;
      $('.animeScreen').fadeIn(function() {
        return $('.adminScreen').fadeOut();
      });
      return this.trigger('conferenceChoosed', confId);
    };

    return Router;

  })(Backbone.Router);
});
