// Generated by CoffeeScript 1.4.0
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['jquery', 'backbone', 'application/views/conferenceView'], function($, Backbone, ConferenceView) {
  var OrganisationView;
  return OrganisationView = (function(_super) {

    __extends(OrganisationView, _super);

    function OrganisationView() {
      return OrganisationView.__super__.constructor.apply(this, arguments);
    }

    OrganisationView.prototype.tagName = 'li';

    OrganisationView.prototype.className = 'organisation';

    OrganisationView.prototype.events = {
      'click .org-item': 'choose',
      'click #deleteorg': 'deleteorg'
    };

    OrganisationView.prototype.template = _.template($('#Organisation-template').html());

    OrganisationView.prototype.initialize = function() {
      var _this = this;
      this.listenTo(this.model, 'change:conferencesC', this.renderConfList);
      return this.listenTo(this.model, 'new', function(data) {
        return _this.renderNew(data);
      });
    };

    OrganisationView.prototype.render = function() {
      this.$el.html(this.template(this.model.toJSON()));
      return this;
    };

    OrganisationView.prototype.renderConfList = function() {
      $('.conf').remove();
      console.log(this.model.get('conferencesC'));
      return this.model.get('conferencesC').each(function(conference) {
        var conferenceView;
        conferenceView = new ConferenceView({
          model: conference
        });
        return $('.confList').prepend(conferenceView.render().el);
      });
    };

    OrganisationView.prototype.renderNew = function(conference) {
      var conferenceView;
      conferenceView = new ConferenceView({
        model: conference
      });
      return $('.confList').prepend(conferenceView.render().el);
    };

    OrganisationView.prototype.choose = function(ev) {
      var href, id;
      $(".organisationsList li").each(function(i, elt) {
        return $(elt).removeClass('active');
      });
      this.$el.addClass('active');
      $('.organisationsList').trigger('organisationChoosed', this.model.get('id'));
      $(".confplus").parent().show();
      id = this.model.get('id');
      href = '/conference/' + id;
      return Backbone.history.navigate(href, {
        trigger: true
      });
    };

    OrganisationView.prototype.deleteorg = function() {
      return $('#deleteorg').trigger('deleteorg', this.model.get('id'));
    };

    return OrganisationView;

  })(Backbone.View);
});
