// Generated by CoffeeScript 1.4.0
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['jquery', 'backbone'], function($, Backbone) {
  var slideView;
  return slideView = (function(_super) {

    __extends(slideView, _super);

    function slideView() {
      return slideView.__super__.constructor.apply(this, arguments);
    }

    slideView.prototype.el = '#appcontainer';

    slideView.prototype.tagName = 'li';

    slideView.prototype.className = 'slide';

    slideView.prototype.template = _.template($('#slide-template').html());

    slideView.prototype.initialize = function() {
      var _this = this;
      this.listenTo(this.model, 'change', this.render());
      $('.toSend>li').on('click', function() {
        return _this.send();
      });
      $('.sent>li').on('click', function() {
        return _this.remove();
      });
      return console.log("slideScreen initilized");
    };

    slideView.prototype.render = function() {
      this.$el.html(this.template(this.model.toJSON()));
      return this;
    };

    slideView.prototype.send = function() {};

    slideView.prototype.remove = function() {};

    return slideView;

  })(Backbone.View);
});
