// Generated by CoffeeScript 1.4.0
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['jquery', 'backbone', 'application/models/conference', 'application/collections/conferences'], function($, Backbone, Conference, Conferences) {
  var Organisation;
  return Organisation = (function(_super) {

    __extends(Organisation, _super);

    Organisation.prototype.defaults = {
      conferencesC: new Conferences()
    };

    function Organisation(aOrg) {
      Organisation.__super__.constructor.call(this, aOrg);
    }

    Organisation.prototype.restore = function(data) {
      var conference, len, x, _i;
      this.get('conferencesC').reset();
      len = data.length - 1;
      if (len >= 0) {
        for (x = _i = 0; 0 <= len ? _i <= len : _i >= len; x = 0 <= len ? ++_i : --_i) {
          console.log("le x vaut " + x);
          conference = new Conference(data[x]);
          conference.set('id', data[x]._id);
          this.get('conferencesC').add(conference);
        }
      }
      return this.trigger('change:conferencesC');
    };

    Organisation.prototype.conferenceChoosed = function(id) {
      var confsFound;
      confsFound = this.get('conferencesC').where({
        _id: id
      });
      this.set('conference', confsFound[0]);
      return console.log('mon choix de conf: ', this.get('conference'));
    };

    Organisation.prototype.createConf = function(data) {
      var conference;
      conference = new Conference(data);
      conference.set('id', data._id);
      this.get('conferencesC').add(conference);
      return this.trigger('new', this.get('conferencesC').get(data._id));
    };

    return Organisation;

  })(Backbone.Model);
});
